app/urls.py
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', RedirectView.as_view(url='cats/list/')),
	path('cats/', include('cats.urls')),
	path('colonies/', include('colonies.urls')),
	path('downloads/', include('downloads.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
	urlpatterns.append( path('__reload__/', include('django_browser_reload.urls')) )

cats/urls.py
from django.urls import path, include
from cats import views

app_name = 'cats'

urlpatterns = [
    path('list/',views.list_view, name='list'),
    path('create/',views.create_view, name='create'),
    path('detail/<int:pk>',views.detail_view, name='detail'),
    path('update/<int:pk>',views.update_view, name='update'),
    path('delete/<int:pk>',views.delete_view, name='delete'),
]

colonies/urls.py
from django.urls import path, include
from colonies import views

app_name = 'colonies'

urlpatterns = [
    path('list/',views.list_view, name='list'),
    path('create/',views.create_view, name='create'),
    path('detail/<int:pk>',views.detail_view, name='detail'),
    path('update/<int:pk>',views.update_view, name='update'),
    path('delete/<int:pk>',views.delete_view, name='delete'),
]

colonies/models.py
from django.db import models

class Colony(models.Model):
    name = models.CharField(max_length=32, verbose_name='Nombre', null=True, blank=True)
    link_gmap = models.URLField(verbose_name='Link Google Maps', null=True, blank=True)
    # image_landscape = models.ImageField(upload_to='colony-landscape', verbose_name='Foto del lugar', blank=True, null=True)
    # localization
    # long - lat ?
    # district

    def __str__(self):
        return self.name

colonies/forms.py
from colonies.models import Colony
from django import forms

class FormColony(forms.ModelForm):
    class Meta:
        model = Colony
        fields = '__all__'

colonies/views.py
from django.shortcuts import render, redirect
from colonies.forms import FormColony
from colonies.models import Colony
from cats.models import Cat

def list_view(request):

    context = dict(list_colony=Colony.objects.all())
    return render(request, 'colonies/list.html', context)


def create_view(request):

    if request.method == 'POST':
        form_colony = FormColony(data=request.POST)
        if form_colony.is_valid():
            form_colony.save()
            return redirect('colonies:list')
    else:
        form_colony = FormColony()
        
    context = dict(
        form_colony = form_colony,
    )
    return render(request, 'colonies/create.html', context)


def detail_view(request,pk):
    colony = Colony.objects.get(id=pk)

    list_cat = Cat.objects.filter(colony=colony)
    list_cat = list_cat.order_by('frequency', 'name')

    context = dict(
        colony=colony,
        list_cat=list_cat
        )
    return render(request, 'colonies/detail.html', context)


def update_view(request,pk):
    colony = Colony.objects.get(id=pk)

    if request.method == 'POST':
        form_colony = FormColony(data=request.POST, instance=colony)
        if form_colony.is_valid():
            colony = form_colony.save()
            return redirect('colonies:detail', pk=pk)
    else:
        form_colony = FormColony(instance=colony)

    # thumbnail_url = colony.thumbnail.url if colony.thumbnail else None
    # context = dict(form_colony = form_colony, pk=pk, thumbnail_url=thumbnail_url)
    context = dict(form_colony = form_colony, pk=pk)
    return render(request, 'colonies/update.html', context)


def delete_view(request,pk):
    colony = Colony.objects.get(id=pk)
    colony.delete()
    return redirect('colonies:list')

colonies/templates/colonies/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nueva Colonia{% endblock %}

{% block links %}
  <link rel='stylesheet' href='{% static "css/forms.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "css/icons.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "colonies/css/create.css" %}?v={{STATIC_VERSION}}'>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>Nueva Colonia</div>
{% endblock %}

{% block content %}
<div class='form-container'>

  <div class='form-body'>
    <form id='form' method='POST'>
        {% csrf_token %}

        <div class='form-list'>
          <div class='form-field'>
            {{form_colony.name.label_tag}}
            {{form_colony.name}}
          </div>

          <div class='form-field div-link-map'>
            {{form_colony.link_gmap.label_tag}}
            <span class='span-link-map'>
              {{form_colony.link_gmap}}
              <a class='btn-icon ic-search' href='https://www.google.com/maps/@39.5719777,2.6284242,14z' target='_blank'></a>
            </span>
          </div>

        </div>
        
    </form>
  </div>

  <div class='form-footer'>
    <div></div>
    <div class='footer-group'>
      <button class='btn-form' onclick='history.back()'>Cancelar</button>
      <button type='submit' form='form' class='btn-form'>Guardar</button>
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
{% endblock %}

colonies/templates/colonies/detail.html

{% extends 'base.html' %}
{% load static %}

{% block title %}Colonia {{colony.name}}{% endblock %}

{% block links %}
  <link rel='stylesheet' href='{% static "css/detail.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "css/list.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "css/option-menu.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "css/dialog.css" %}?v={{STATIC_VERSION}}'>
{% endblock %}

{% block btn_back %}
  <a class='icon btn-icon ic-back' href='{% url "colonies:list" %}'></a>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>{{colony.name}}</div>
{% endblock %}

{% block nav_right_options %}
  <button id='btn-option-menu' class='icon btn-icon ic-more'></button>
{% endblock %}

{% block content %}

<div class='detail-container'>
  
  <div class='detail-list-wrapper'>

    <div class='detail-list'>  
      <label>Nombre</label>
      <span>{{colony.name}}</span>
      
      <label>Link Google Maps</label>
      <a href={{colony.link_gmaps}}></a>
    </div>
  
  </div>
  
  {% if list_cat %}

  <div class='list-scroll'>
    <div class='list-container'>
      {% for cat in list_cat %}
        <a class='list-item' href='{% url "cats:detail" pk=cat.id %}'>
          <div class='thumbnail-wrapper'>
            <img class='list-item-thumbnail' src='{% if cat.thumbnail %}{{cat.thumbnail.url}}{% endif %}'>
          </div>
          <div class='list-fields'>
            <span class='list-item-name'>
              {{cat.name}}
              {% if cat.sterilized %}
                <i class='icon icon-small {% if cat.gender %}ic-female-neutered{% else %}ic-male-neutered{% endif %}'></i>
              {% else %}
                <i class='icon icon-small {% if cat.gender %}ic-female{% else %}ic-male{% endif %}'></i>
              {% endif %}
            </span>
          </div>
        </a>
      {% endfor %}
    </div>
    {% else %}
    <span class='span-message'>No hay gatos<br>en esta colonia</span>
    {% endif %}
  </div>
</div>

{% endblock %}

{% block option_menu %}
    <div id='option-menu' style='display:none'>
    <ul class='option-menu-list'>
      <li id='option-edit' data='{% url "colonies:update" pk=colony.id %}'>Editar</li>
      <li id='option-delete'>Eliminar</li>
    </ul>
  </div>
{% endblock %}

{% block modal %}
  <!-- <div id='modal' class='modal-wrapper'> -->
  <div id='modal' class='modal-wrapper' style='display:none;'>
    <div class='modal-container'>
      <header class='modal-header'>Eliminar colonia</header>
      <div class='modal-body'>¿Seguro que quiere elimintar esta colonia?</div>
      <footer class='modal-footer'>
        <button id='btn-positive' data='{% url "colonies:delete" pk=colony.id %}'>Aceptar</button>
        <button id='btn-negative'>Cancelar</button>
      </footer>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script type='text/javascript' src='{% static "js/option-menu.js" %}'></script>
  <script type='text/javascript' src="{% static 'js/modal.js' %}"></script>
  <script type='text/javascript' src='{% static "colonies/js/detail.js" %}'></script>
{% endblock %}

colonies/templates/colonies/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Colonias{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/list.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/icons.css' %}?v={{STATIC_VERSION}}">
{% endblock %}

{% block header_title %}
  <div class='nav-title'>Colonias</div>
{% endblock %}

{% block nav_right_options %}
  <a href="{% url 'colonies:create' %}"><i class='btn-icon ic-add'></i></a>
{% endblock %}

{% block content %}

  {% if list_colony %}
    <div class="list-container">
      {% for colony in list_colony %}
        <a class='list-item' href='{% url "colonies:detail" pk=colony.id %}'>
          <div class='list-fields' >
            <span class='list-item-name'>{{colony.name}}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <span class='span-message'>Pulsa + para<br>añadir colonias</span>
  {% endif %}
{% endblock %}

colonies/templates/colonies/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Colonia{% endblock %}

{% block links %}
  <link rel='stylesheet' href='{% static "css/forms.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "colonies/css/create.css" %}?v={{STATIC_VERSION}}'>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>Editar</div>
{% endblock %}

{% block content %}

  <div class='form-container'>

    <div class='form-body'>
      <form id='form' method='POST' enctype='multipart/form-data'>
          {% csrf_token %}

          <div class='form-list'>
            {% for field in form_colony %}
              <div class='form-field'>
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
              </div>
            {% endfor %}

          </div>

      </form>
    </div>

    <div class='form-footer'>
      <div></div>
      <div class='footer-group'>
        <a type='button' class='btn-form' href='{% url "colonies:detail" pk=pk %}'>Cancelar</a>
        <button type='submit' form='form' class='btn-form'>Guardar</button>
      </div>
    </div>

  </div>

{% endblock %}

{% block modal %}

  <div id='div-crop-container' style='display:none'>
    <div class='div-crop-area'>
      <img id='image-crop' src=''>
    </div>
    <div class='cropper-footer'>
      <span id='btn-crop-close' class='btn-crop'>Cancelar</span>
      <span id='btn-crop-save' class='btn-crop'>Aplicar</span>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  
{% endblock %}