app/urls.py
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', RedirectView.as_view(url='cats/list/')),
	path('cats/', include('cats.urls')),
	path('colonies/', include('colonies.urls')),
	path('downloads/', include('downloads.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
	urlpatterns.append( path('__reload__/', include('django_browser_reload.urls')) )

cats/urls.py
from django.urls import path, include
from cats import views

app_name = 'cats'

urlpatterns = [
    path('list/',views.list_view, name='list'),
    path('create/',views.create_view, name='create'),
    path('detail/<int:pk>',views.detail_view, name='detail'),
    path('update/<int:pk>',views.update_view, name='update'),
    path('delete/<int:pk>',views.delete_view, name='delete'),
]

downloads/urls.py
from django.urls import path, include
from downloads import views

app_name = 'downloads'

urlpatterns = [
    path('census',views.download_census, name='census'),
]

cats/models.py
from colonies.models import Colony
from diseases.models import Disease
from django.db import models
from cats import utils
import pdb
import os

T_SEX_CHOICES = ((False, 'Macho'), (True, 'Hembra'))
T_STATE_CHOICES = ((0, 'Presente'), (1, 'Fallecido'),(2, 'Desaparecido'),(3,'Adoptado'))
T_YES_NO = ((False,'No'),(True,'Sí'))
T_FREQUENCY = ((0,'Habitual'),(1,'Ocasional'))
T_SOCIABILITY = ((0,'Sí'),(1,'Ocasional'),(2,'No'))
T_AGES = ((0,'Adulto'),(1,'Joven'),(2,'Bebé'))

class Cat(models.Model):
    photo = models.ImageField(upload_to='cat-photos', verbose_name='Icono', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='cat-thumbnails', verbose_name='Icono', blank=True, null=True)
    
    name = models.CharField(max_length=32, blank=True, null=True, verbose_name='Nombre')
    colony = models.ForeignKey(to=Colony, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Colonia')
    gender = models.BooleanField(choices=T_SEX_CHOICES, blank=True, null=True, verbose_name='Sexo')
    # sterilized = models.BooleanField(choices=T_YES_NO, blank=True, null=True, verbose_name='Esterilizado')
    sterilized = models.BooleanField(blank=False, default=False, verbose_name='Esterilizado')
    
    # Advanced Options
    sterlize_date = models.DateField(blank=True, null=True, verbose_name='Fecha de esterilización')
    state = models.PositiveSmallIntegerField(blank=True, null=True, choices=T_STATE_CHOICES, default=0, verbose_name='Estado')
    frequency = models.PositiveSmallIntegerField(blank=True, null=True, choices=T_FREQUENCY, verbose_name='Frecuencia de visita', default=0)
    age = models.PositiveSmallIntegerField(blank=True, null=True, choices=T_AGES,  verbose_name='Edad', default=0)
    sociability = models.PositiveSmallIntegerField(blank=True, null=True, choices=T_SOCIABILITY, verbose_name='Sociable', default=1)
    sighting_date = models.DateField(verbose_name='Fecha de avistamiento', blank=True, null=True)
    disease = models.ForeignKey(to=Disease, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Afecciones')
    
    record_date = models.DateField(auto_now=True, verbose_name='Fecha de registro', blank=True, null=True)
    pictures = models.ManyToManyField(to='CatPicture', related_name='cats', blank=True)
    # tray_picture = models.ForeignKey(to='CatPicture', related_name='tray_for_cat', on_delete=models.SET_NULL, null=True, blank=True)

    def delete(self, *args, **kwargs):
        for picture in self.pictures.all():
            picture.delete(save=False)

        if self.photo and os.path.isfile(self.photo.path):
            self.photo.delete(save=False)
        
        # pdb.set_trace()

        if self.thumbnail and os.path.isfile(self.thumbnail.path):
            self.thumbnail.delete(save=False)

        super().delete(*args, **kwargs)


    def save(self, *args, **kwargs):
        if self.id:
            cat = Cat.objects.get(id=self.id)
            if self.photo and self.photo != cat.photo:
                if cat.photo and os.path.isfile(cat.photo.path):
                    cat.photo.delete(save=False)
                if cat.thumbnail and os.path.isfile(cat.thumbnail.path):
                    cat.thumbnail.delete(save=False)

        super().save(*args, **kwargs)

    # def save(self, *args, **kwargs):
    #     if self.id:
    #         cat = Cat.objects.get(id=self.id)
    #         if self.photo and self.photo != cat.photo:
    #             if cat.photo and os.path.isfile(cat.photo.path):
    #                 cat.photo.delete(save=False)
    #             if cat.thumbnail and os.path.isfile(cat.thumbnail.path):
    #                 cat.thumbnail.delete(save=False)
    #             photo = self.photo
    #         else:
    #             photo = cat.photo
    #     else:
    #         super().save(*args, **kwargs)
    #         photo = self.photo

    #     bytes_io = utils.to_thumbnail(photo)
    #     file_name = utils.format_image_name(self.id)
    #     self.thumbnail.save(name=file_name, content=bytes_io, save=False)

    #     super().save(*args, **kwargs)

class CatPicture(models.Model):
    image = models.ImageField(upload_to='cats', verbose_name='Foto')
    date = models.DateField(verbose_name='Fecha', blank=True, null=True)

    def delete(self, *args, **kwargs):
        self.image.delete()  # This deletes the real image aswell
        super(CatPicture, self).delete(*args, **kwargs)

cats/forms.py
from cats.models import Cat, CatPicture
from django import forms


class FormCat(forms.ModelForm):

    class Meta:
        model = Cat
        exclude = ('pictures','thumbnail')
        widgets = {
            'photo': forms.FileInput(attrs={'style': 'display:none;'}),
            'sterlize_date': forms.DateInput(attrs={'type': 'date'}),
            'sighting_date': forms.DateInput(attrs={'type': 'date'}),
        }


T_STERILIZED_CHOICES = ( (None,'----'), (True, 'Sí'), (False, 'No') )

class FormCatFilter(forms.ModelForm):

    sterilized = forms.ChoiceField(choices=T_STERILIZED_CHOICES, initial=True, required=False, label='Esterilizado')

    class Meta:
        model = Cat
        exclude = ('photo','thumbnail','pictures','sighting_date','sterlize_date','record_date')
        # fields = ('colony','gender','sterilized','frequency','state','sociability')

# class FormCatPicture(forms.ModelForm):

#     class Meta:
#         model = CatPicture
#         fields = ('image',)
#         widgets = {
#             'image': forms.FileInput(attrs={'style': 'display:none;'}),
#         }

cats/views.py
from django.shortcuts import render, redirect
from cats.forms import FormCat, FormCatFilter
from downloads.forms import FormCensus
from django.db.models import Count, Q
from colonies.models import Colony
from django.urls import reverse
from cats.models import Cat
from cats import utils
import pdb


def create_view(request):

    if request.method == 'POST':
        form_cat = FormCat(data=request.POST, files=request.FILES)
        if form_cat.is_valid():
            instance = form_cat.save(commit=True)
            
            if 'photo' in request.FILES:
                file_photo = request.FILES['photo']
              
                bytes_photo = utils.to_webp(image_file=file_photo)
                bytes_thumbnail = utils.to_thumbnail_webp(image_file=file_photo)
                
                file_name = utils.format_image_name(cat_id=instance.id)
                instance.photo.save(name=file_name, content=bytes_photo, save=False)
                instance.thumbnail.save(name=file_name, content=bytes_thumbnail, save=False)
                instance.save()
                
            return redirect('cats:list')
    else:
        d_query = request.session.get('query_cat',{})
        form_cat = FormCat(initial=d_query)

    context = dict(form_cat = form_cat)
    return render(request, 'cats/create.html', context)


def list_view(request):

    if request.GET:
        d_query = request.GET.dict()
        if 'filter' in d_query:
            del d_query['filter']
        request.session['query_cat'] = d_query
    else:
        d_query = request.session.get('query_cat',{})
        if 'filter' in d_query:
            del d_query['filter']

    form_cat_filter = FormCatFilter(data=d_query)
    
    d_query = {k: v for k, v in d_query.items() if v}
    
    if 'name' in d_query:
        d_query['name__contains'] = d_query.pop('name')

    records = Cat.objects.filter(**d_query)
    records = records.order_by('frequency', 'name')
    
    d_aggregate = records.aggregate(
        total_cats = Count('id'),
        n_neutered = Count('id', filter=Q(sterilized=True)),
        n_males = Count('id', filter=Q(gender=False)),
        n_females = Count('id', filter=Q(gender=True)),
        males_neutered = Count('id', filter=Q(gender=False, sterilized=True)),
        females_neutered = Count('id', filter=Q(gender=True, sterilized=True)),
    )

    context = dict(
        list_cat=records,
        form_cat_filter=form_cat_filter,
        form_census=FormCensus(initial={'colony' : d_query.get('colony')}),
        **d_aggregate
    )
    
    if 'colony' in d_query:
        context['colony'] = Colony.objects.get(id=d_query['colony'])

    return render(request, 'cats/list.html', context)


def detail_view(request,pk):
    cat = Cat.objects.get(id=pk)
    context = dict(cat=cat)
    return render(request, 'cats/detail.html', context)


def update_view(request,pk):
    cat = Cat.objects.get(id=pk)

    if request.method == 'POST':
        form_cat = FormCat(data=request.POST, files=request.FILES, instance=cat)
        if form_cat.is_valid():
            instance = form_cat.save(commit=False)
            
            if 'photo' in request.FILES:
            
                file_photo = request.FILES['photo']
                bytes_photo = utils.to_webp(image_file=file_photo)
                bytes_thumbnail = utils.to_thumbnail_webp(image_file=file_photo)
                
                file_name = utils.format_image_name(cat_id=cat.id)
                instance.photo.save(name=file_name, content=bytes_photo, save=False)
                instance.thumbnail.save(name=file_name, content=bytes_thumbnail, save=False)

            instance.save()

            return redirect('cats:detail', pk=pk)
    else:
        form_cat = FormCat(instance=cat)

    photo_url = cat.photo.url if cat.photo else None
    context = dict(form_cat = form_cat, pk=pk, photo_url=photo_url)
    return render(request, 'cats/update.html', context)


def delete_view(request,pk):
    cat = Cat.objects.get(id=pk)
    cat.delete()
    return redirect('cats:list')

cats/templates/cats/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nuevo Gato{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'cats/css/image-cropper.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/forms.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/icons.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'cats/css/create.css' %}?v={{STATIC_VERSION}}">
{% endblock %}

{% block btn_back %}
  <a class='btn-icon ic-back' href='{% url "cats:list" %}'></a>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>Nuevo Gato</div>
{% endblock %}

{% block content %}

  <div class='form-container'>

    <div class='form-body'>
      <form id='form' method='POST' enctype='multipart/form-data'>
          {% csrf_token %}

            {{form_cat.photo}}
            <div id='btn-image-placeholder'>
              <i id='ic-image-placeholder' class='icon ic-image-placeholder'></i>
              <img id='image-tray' src='' style='display:none;'>
            </div>

          <div class='form-table'>
            {% for field in form_cat.visible_fields|slice:"1:4" %}
              <div class="form-field">
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
              </div>
            {% endfor %}
          
            <div class='form-side'>
                {{form_cat.sterilized.label_tag}}
                {{form_cat.sterilized}}
            </div>

          </div>
          
          <div id='btn-show-more' class='btn-form'>Mostrar más</div>
          
          <div id='hidden-panel' class='form-list' style='display: none;'>
            
            {% for field in form_cat.visible_fields|slice:"5:" %}
              <div class="form-field">
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
              </div>    
            {% endfor %}
          
          </div>

          
      </form>
    </div>

    <div class="form-footer">
      <div></div>
      <div class='footer-group'>
        <a class='btn-form' href='{% url "cats:list" %}'>Cancelar</a>
        <button type="submit" form="form" class="btn-form">Guardar</button>
      </div>
    </div>

  </div>

{% endblock %}

{% block modal %}

  <div id='div-crop-container' style='display:none'>
    <div class='div-crop-area'>
      <img id='image-crop' src=''>
    </div>
    <div class='cropper-footer'>
      <span id='btn-crop-close' class='btn-crop'>Cancelar</span>
      <span id='btn-crop-save' class='btn-crop'>Aplicar</span>
    </div>
  </div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/cropper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'cats/js/image-cropper.js' %}"></script>
<script type="text/javascript" src="{% static 'cats/js/create.js' %}"></script>
{% endblock %}

cats/templates/cats/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nuevo Gato{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/icons.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/detail.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/option-menu.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/dialog.css' %}?v={{STATIC_VERSION}}">
{% endblock %}

{% block btn_back %}
  <a class='btn-icon ic-back' href='{% url "cats:list" %}'></a>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>{{cat.name}}</div>
{% endblock %}

{% block nav_right_options %}
  <button id='btn-option-menu' class='btn-icon ic-more'></button>
{% endblock %}

{% block content %}
  <div class='detail-container'>
    
    <img class='detail-image-wrapper' src='{% if cat.photo %}{{cat.photo.url}}{% endif %}'>
    
    <div class='separator'></div>

    <div class='detail-list-wrapper'>
      
      <div class='detail-list'>  
        <label>Colonia</label>
        <span>{% if cat.colony %}{{cat.colony}}{% else %}Sin Colonia{% endif %}</span>
        
        <label>Sexo</label>
        <span>{{cat.get_gender_display}}</span>

        <label>Esterilizado</label>
        <span>
          {% if cat.sterilized %}Sí{% else %}No{% endif %}
          <span class='span-date'>{% if cat.sterilized and cat.sterlize_date %}({{cat.sterlize_date|date:"d/m/y"}}){% endif %}</span>
        </span>
        
        <label>Frecuencia</label>
        <span>{{cat.get_frequency_display}}</span>

        <label>Sociabilidad</label>
        <span>{{cat.get_sociability_display}}</span>

        <label>Estado</label>
        <span>{{cat.get_state_display}}</span>

      </div>
    
      <hr class='hline'>
    
      <div class='detail-list'>
          
        <label>Edad</label>
        <span>{% if cat.get_age_display %}{{cat.get_age_display}}{% else %}-{% endif %}</span>

        <label>Avistamiento</label>
        <span>{{cat.sighting_date|date:"d/m/y"}}</span>

        <label>Registro</label>
        <span>{{cat.record_date|date:"d/m/y"}}</span>

        <label>Enfermedades</label>
        <span></span>

      </div>
    </div>
  </div>
{% endblock %}

{% block option_menu %}
  <div id='option-menu' style='display:none'>
    <ul class='option-menu-list'>
      <li id='option-edit' data='{% url "cats:update" pk=cat.id %}'>Editar</li>
      <li id='option-delete'>Eliminar</li>
    </ul>
  </div>
{% endblock %}

{% block modal %}
  <!-- <div id='modal' class='modal-wrapper'> -->
  <div id='modal' class='modal-wrapper' style='display:none;'>
    <div class='modal-container'>
      <header class='modal-header'>Eliminar gato</header>
      <div class='modal-body'>¿Seguro que quiere eleminar este gato?</div>
      <footer class='modal-footer'>
        <button id='btn-positive' data='{% url "cats:delete" pk=cat.id %}'>Aceptar</button>
        <button id='btn-negative'>Cancelar</button>
      </footer>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script type='text/javascript' src="{% static 'js/option-menu.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/modal.js' %}"></script>
  <script type='text/javascript' src="{% static 'cats/js/detail.js' %}"></script>
{% endblock %}

cats/templates/cats/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cats{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/list.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/icons.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'css/option-menu.css' %}?v={{STATIC_VERSION}}">
  <link rel="stylesheet" href="{% static 'cats/css/modal-form-filter.css' %}?v={{STATIC_VERSION}}">
{% endblock %}

{% block header_title %}
  <div class='nav-title'>{% if colony %}{{colony.name}}{% else %}Gatos{% endif %}</div>
{% endblock %}

{% block nav_right_options %}
  <button onclick='toggleModalFilter()' class='btn-icon ic-filter'></button>
  <a class='btn-icon ic-add' href="{% url 'cats:create' %}"></a>
  <button id='btn-option-menu' class='btn-icon ic-more'></button>
{% endblock %}

{% block content %}

  <div class='sub-info-bar'>  
    <span class='sub-info-group'>
      
      <span class='sub-info-pair'>
        <i class='icon icon-small ic-female-neutered'></i>
        <strong class='sub-info-value'>{{females_neutered}}/{{n_females}}</strong>
      </span>
    
      <span class='sub-info-pair'>
        <i class='icon icon-small ic-male-neutered'></i>
        <strong class='sub-info-value'>{{males_neutered}}/{{n_males}}</strong>
      </span>
    </span>

    <span class='sub-info-group'>
    
      <span class='sub-info-pair'>
        <strong class='sub-info-value'>{{n_neutered}}/{{total_cats}}</strong>
      </span>
    </span>
  </div>

  {% if list_cat %}
  <div class='list-scroll'>
    <div class='list-container'>
      {% for cat in list_cat %}
        <a class='list-item' href='{% url "cats:detail" pk=cat.id %}'>
          <div class='thumbnail-wrapper'>
            <img class='list-item-thumbnail' src='{% if cat.thumbnail %}{{cat.thumbnail.url}}{% endif %}' loading='lazy'>
          </div>
          <div class='list-fields'>
            <span class='list-item-name'>
              {{cat.name}}
              {% if cat.gender is None %}
              <i>-</i>
              {% else %}
                {% if cat.sterilized %}
                  <i class='icon icon-small {% if cat.gender %}ic-female-neutered{% else %}ic-male-neutered{% endif %}'></i>
                {% else %}
                  <i class='icon icon-small {% if cat.gender %}ic-female{% else %}ic-male{% endif %}'></i>
                {% endif %}
              {% endif %}
            </span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>

  {% else %}
    <span class='span-message'>Pulsa + para<br>añadir gatos</span>
  {% endif %}
    
{% endblock %}

{% block option_menu %}
  <div id='option-menu' style='display:none'>
    <ul class='option-menu-list'>
      <li id='option-create-census'>Generar Censo</li>
    </ul>
  </div>
{% endblock %}

{% block modal %}

  <div id='modal-filter' class='modal-form-wrapper' style='display:none'>
  <!-- <div id='modal-filter' class='modal-form-wrapper'> -->
    <div class='modal-form-container'>
      <div class='modal-form-header'>
        Filtros
        <button id='btn-modal-close' class='btn-modal-close'>&#x2A2F</button>
      </div>
      <form id='form-filter' method='GET' action='{% url "cats:list" %}'>
        <input type='hidden' name='filter' value='true'>
        <div class='modal-form-body'>
          {% for field in form_cat_filter.visible_fields|slice:"0:3" %}
              {{field.label_tag}}
              {{field}}
          {% endfor %}
        </div>

        <button id='btn-show-more' type='button' onclick='toggleAdvancedForm()'>Mostrar más</button>
        
        <div id='div-advanced-form' class='modal-form-body' style='display:none'>
            {% for field in form_cat_filter.visible_fields|slice:"3:" %}
              {{field.label_tag}}
              {{field}}
          {% endfor %}
        </div>
      </form>
      <div class='modal-form-footer'>
        <a class='btn-modal-submit' href='{% url "cats:list" %}?filter=true'>Reset</a>
        <input type='submit' form='form-filter' value='Buscar' class='btn-modal-submit'>
      </div>
    </div>
  </div>

  <div id='modal-census' class='modal-form-wrapper' style='display:none'>
  <!-- <div id='modal-census' class='modal-form-wrapper'> -->
    <div class='modal-form-container'>
      <div class='modal-form-header'>
        Crear censo
        <button id='btn-modal-close' class='btn-modal-close'>&#x2A2F</button>
      </div>
      <form id='form-census' method='POST' action='{% url "downloads:census" %}'>
        {% csrf_token %}
        <div class='modal-form-body'>
          {% for field in form_census %}
              {{field.label_tag}}
              {{field}}
          {% endfor %}
        </div>
      </form>
      <div class='modal-form-footer'>
        <div></div>
        <input type='submit' form='form-census' value='Crear' class='btn-modal-submit'>
      </div>
    </div>
  </div>
  
{% endblock %}

{% block scripts %}
  <script type='text/javascript' src="{% static 'js/option-menu.js' %}"></script>
  <script type='text/javascript' src='{% static "cats/js/modal-form-filter.js" %}'></script>
  <script type='text/javascript' src='{% static "cats/js/list.js" %}'></script>
{% endblock %}

cats/templates/cats/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Gato{% endblock %}

{% block links %}
  <link rel='stylesheet' href='{% static "css/cropper.min.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "cats/css/image-cropper.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "css/forms.css" %}?v={{STATIC_VERSION}}'>
  <link rel='stylesheet' href='{% static "cats/css/create.css" %}?v={{STATIC_VERSION}}'>
{% endblock %}

{% block btn_back %}
  <a class='btn-icon ic-back' href='{% url "cats:detail" pk=pk %}'></a>
{% endblock %}

{% block nav_right_options %}
  <button type='submit' form='form' class='icon btn-icon ic-save'></button>
{% endblock %}

{% block header_title %}
  <div class='nav-title'>Editar</div>
{% endblock %}

{% block content %}

  <div class='form-scroll'>
    <div class='form-container'>
      <div class='form-body'>
        <form id='form' method='POST' enctype='multipart/form-data'>
          {% csrf_token %}
          <div class='form-list'>
            <div class='form-field'>
              {{form_cat.photo.label_tag}}
              {{form_cat.photo}}
              <div id='btn-image-placeholder'>
                <i id='ic-image-placeholder' class='icon ic-image-placeholder'></i>
                  <img id='image-tray' src='{% if photo_url %}{{photo_url}}{% endif %}'>
              </div>
            </div>

            {% for field in form_cat.visible_fields|slice:'1:4' %}
              <div class='form-field'>
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
              </div>
            {% endfor %}
          
            <div class='form-side'>
                {{form_cat.sterilized.label_tag}}
                {{form_cat.sterilized}}
            </div>

          </div>

          <hr class='hline'>

          <div class='form-list'>
            
            {% for field in form_cat.visible_fields|slice:'5:' %}
              <div class='form-field'>
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
              </div>    
            {% endfor %}
          
          </div>

          
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block modal %}

  <div id='div-crop-container' style='display:none'>
    <div class='div-crop-area'>
      <img id='image-crop' src=''>
    </div>
    <div class='cropper-footer'>
      <span id='btn-crop-close' class='btn-crop'>Cancelar</span>
      <span id='btn-crop-save' class='btn-crop'>Aplicar</span>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script type='text/javascript' src='{% static "js/cropper.min.js" %}'></script>
  <script type='text/javascript' src='{% static "cats/js/image-cropper.js" %}'></script>
  <script type='text/javascript' src='{% static "cats/js/create.js" %}'></script>
{% endblock %}