app/urls.py
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', RedirectView.as_view(url='cats/list/')),
	path('cats/', include('cats.urls')),
	path('colonies/', include('colonies.urls')),
	path('downloads/', include('downloads.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
	urlpatterns.append( path('__reload__/', include('django_browser_reload.urls')) )

cats/urls.py
from django.urls import path, include
from cats import views

app_name = 'cats'

urlpatterns = [
    path('list/',views.list_view, name='list'),
    path('create/',views.create_view, name='create'),
    path('detail/<int:pk>',views.detail_view, name='detail'),
    path('update/<int:pk>',views.update_view, name='update'),
    path('delete/<int:pk>',views.delete_view, name='delete'),
]

colonies/urls.py
from django.urls import path, include
from colonies import views

app_name = 'colonies'

urlpatterns = [
    path('list/',views.list_view, name='list'),
    path('create/',views.create_view, name='create'),
    path('detail/<int:pk>',views.detail_view, name='detail'),
    path('update/<int:pk>',views.update_view, name='update'),
    path('delete/<int:pk>',views.delete_view, name='delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset='UTF-8'>
		<meta name='viewport' content='width=device-width, initial-scale=1'>
		
		<title>{% block title %}AMBIT{% endblock %}</title>

		<link rel='stylesheet' href='{% static "css/base.css" %}?v={{STATIC_VERSION}}'>
		<link rel='stylesheet' href='{% static "css/icons.css" %}?v={{STATIC_VERSION}}'>

		{% block links %}{% endblock %}
		
		{% block styles %}{% endblock %}

	</head>

	<body>
		<nav class='nav-top'>
			<div class='nav-pack'>
				<button class='btn-icon ic-menu' onclick='openNav()'></button>
				{% block btn_back %}{% endblock %}
			</div>
			{% block header_title %}{% endblock %}
			<div class='nav-pack'>
				{% block nav_right_options %}{% endblock %}
			</div>
		</nav>

		<main>
			{% block content %}{% endblock %}
			{% block option_menu %}{% endblock %}
		</main>

		<!-- <aside id='side-bar' class='side-bar-dimmed'> -->
		<aside id='side-bar' class='side-bar-dimmed' style='display:none'>
	    	<nav class='side-bar'>
	    		<header class='side-bar-header'>
	    			<span class='side-bar-header-title'>AMBIT</span>
					<button class='btn-side-bar-close' onclick='closeNav()'>&#x2A2F</button>
	    		</header>
			    <ul class='list-nav'>
			      	{% with request.path as url %}
				        <a href='{% url "colonies:list" %}' class="{% if 'colonies' in url %}active{% endif %}">Colonias</a>
				        <a href='{% url "cats:list" %}' class="{% if 'cats' in url %}active{% endif %}">Gatos</a>
			        {% endwith %}
			    </ul>
		    </nav>
		</aside>

		{% block modal %}{% endblock %}

	</body>

	<script type="text/javascript" src='{% static "js/base.js" %}'></script>
	{% block scripts %}{% endblock %}

</html>